// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWF1yENDNPpp4Dtv_UpSRLgM8r2fIt64I',
    appId: '1:909647201341:web:ce12784fad973bfaedd654',
    messagingSenderId: '909647201341',
    projectId: 'tienda-9d098',
    authDomain: 'tienda-9d098.firebaseapp.com',
    storageBucket: 'tienda-9d098.appspot.com',
    measurementId: 'G-817FYSXL2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPtoSwq3xhNGdeQjX8UIzTRjFsMw0s2o',
    appId: '1:909647201341:android:49058997ec01ef6dedd654',
    messagingSenderId: '909647201341',
    projectId: 'tienda-9d098',
    storageBucket: 'tienda-9d098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITmFE5-YU1hQ2bBG5CWmxy-MT8cisfYw',
    appId: '1:909647201341:ios:78ad8d19897a7e6fedd654',
    messagingSenderId: '909647201341',
    projectId: 'tienda-9d098',
    storageBucket: 'tienda-9d098.appspot.com',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCITmFE5-YU1hQ2bBG5CWmxy-MT8cisfYw',
    appId: '1:909647201341:ios:78ad8d19897a7e6fedd654',
    messagingSenderId: '909647201341',
    projectId: 'tienda-9d098',
    storageBucket: 'tienda-9d098.appspot.com',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWF1yENDNPpp4Dtv_UpSRLgM8r2fIt64I',
    appId: '1:909647201341:web:efb264523cd02ad5edd654',
    messagingSenderId: '909647201341',
    projectId: 'tienda-9d098',
    authDomain: 'tienda-9d098.firebaseapp.com',
    storageBucket: 'tienda-9d098.appspot.com',
    measurementId: 'G-V20FRYCT4J',
  );
}
